- name: install packages facilitating password hardening
  package: name="{{ item }}" state=present
  with_items:
    - libpam-passwdqc

- name: set password max/min/warn age for accounts created in future
  lineinfile:
    dest: /etc/login.defs
    line: "{{ item.key }}	{{ item.value }}"
    regexp: '^\s*{{ item.key }}\s.*'
  with_items:
    - { key: "PASS_MAX_DAYS", value: "{{ pass_max_days }}"}
    - { key: "PASS_MIN_DAYS", value: "{{ pass_min_days }}"}
    - { key: "PASS_WARN_AGE", value: "{{ pass_warn_age }}"}

- name: set password max/min/warn age for existing accounts w/ a password set
  shell: "awk -F: '{print $2\":\"$1}' /etc/shadow
          | egrep '^[^\\!\\*:]'
          | cut -d: -f2
          | xargs -rL1 chage -m '{{ pass_min_days }}'
                             -M '{{ pass_max_days }}'
                             -W '{{ pass_warn_age }}'"

- name: provide legal banner pre logins
  file: path="{{ item }}"
        src=/opt/admintools/pre-login-banner.txt
        state=link force=yes
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: hide PIDs between users
  mount: src=proc name=/proc fstype=proc opts=defaults,hidepid=2
         dump=0 passno=0 state=present
  when: ansible_kernel is version_compare('3.3', '>=') and
        hide_processes_between_users

- name: unhide PIDs between users
  mount: src=proc name=/proc fstype=proc opts=defaults,hidepid=2
         dump=0 passno=0 state=absent
  when: ansible_kernel is version_compare('3.3', '<') or
        not hide_processes_between_users
  # hotfix: tries to delete /proc ...
  ignore_errors: yes
