- name: set localhost v4 and v6 addresses in /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp="^\s*{{ item.ip|regex_escape }}\s+.*{{ item.host|regex_escape }}(\s.*|$)"
              line="{{ item.ip }} {{ item.host }}"
  with_items:
    - ip: 127.0.0.1
      host: localhost ip4-localhost ip4-loopback
    - ip: ::1
      host: localhost ip6-localhost ip6-loopback
    - ip: ff02::1
      host: ip6-allnodes
    - ip: ff02::2
      host: ip6-allrouters
    - ip: fe00::0
      host: ip6-localnet
    - ip: ff00::0
      host: ip6-mcastprefix

- name: set v4 and v6 address for fqdn in /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp="^\s*{{ item.address|regex_escape }}.*\s*({{ ansible_fqdn|regex_escape }}|{{ ansible_hostname|regex_escape }})[\s$].*"
              line="{{ item.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  when: item and ansible_form_factor != "Notebook"
  with_items:
    - "{{ ansible_default_ipv4 }}"
    - "{{ ansible_default_ipv6 }}"

- name: ensure lookup in /etc/hosts before dns
  lineinfile: line="order hosts,bind"
              regexp="^\s*order\s.*"
              dest="/etc/host.conf"
              insertbefore="^\s*multi\s.*"

- name: set nameservers
  blockinfile:
    dest: /etc/resolv.conf
    state: present
    insertbefore: BOF
    create: yes
    mode: 0644
    block: "nameserver {{ nameservers|join('\nnameserver ') }}"
  when: nameservers

- name: install DNS utilities
  package: name="{{ item }}"
  with_items:
    - namebench
    - dnsutils
