- name: install hardware analyses and monitoring tools
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  with_dict: "{{ hardware_analysis_and_monitoring_packages |
                 combine(hardware_analysis_and_monitoring_packages_extra |
                         default({})) }}"
