[master]
10.0.0.1 piname=node01 yarnmaximummemory=3027 yarnminimummemory=256 yarnammemory=512 yarnmrmemory=256 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[cluster]
10.0.0.2 piname=node02 yarnmaximummemory=512 yarnminimummemory=256 yarnammemory=256 yarnmrmemory=128 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
10.0.0.3 piname=node03 yarnmaximummemory=512 yarnminimummemory=256 yarnammemory=256 yarnmrmemory=128 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
10.0.0.4 piname=node04 yarnmaximummemory=512 yarnminimummemory=256 yarnammemory=256 yarnmrmemory=128 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
10.0.0.5 piname=node05 yarnmaximummemory=512 yarnminimummemory=256 yarnammemory=256 yarnmrmemory=128 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

