---
hadoop:
  version: 3.1.3
  hadoop_archive: hadoop-3.1.3.tar.gz
  data_dir: /home/hadoop/data/dataNode
  name_dir: /home/hadoop/data/nameNode
  temp_dir: /tmp/hadoop/hdfs/tmp
  download_location: https://archive.apache.org/dist/hadoop/common/
  user: hadoop
  user_shell: /bin/zsh
  default_hosts:
    - node01
  replication_factor: 3
  blocksize: 33554432
hadoop_install_dir: "/home/hadoop/hadoop"
hadoop_master_ip: node01
master_nodes: "{% if 'master' in groups %} {{ groups['master']|length }} {% else  %} 0 {% endif %}"
data_nodes: "{% if 'cluster' in groups %} {{ groups['cluster']|length }} {% else  %} 0 {% endif %}"
number_of_nodes: "{{ master_nodes + data_nodes }}"
ssh_key_filename: "id_rsa"
install_temp_dir: "/tmp/hadoop-temp"
is_master: false
is_node: true
yarnmrheapratio: 0.7
